routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('imagecache/{template}/{filename}', [
    'uses' => 'ImageCacheController@getResponse',
    'as'   => 'imagecache'
])->where('filename', '[ \w\\.\\/\\-\\@]+');

//Route::get('/lp/{filename}', function ($filename) {
//    return view('frontend.lp.' . $filename);
//});

Tools::includeRoutes('Frontend');

Route::group(['namespace' => 'Backend', 'prefix' => 'admin'], function () {
    Tools::includeRoutes('Backend');
});

Route::get('{slug}', [
    'uses' => 'Frontend\IndexController@view',
])->where('slug', '([A-Za-z0-9\-\/\_]+)');

app/Models/Acl/User.php
<?php

namespace App\Models\Acl;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use App\Traits\Validatorable;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use Notifiable,
        EntrustUserTrait,
        Validatorable;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'users';

    protected $connection = 'mysql';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'last_name', 'first_name', 'phone', 'address', 'city', 'country', 'email', 'password', 'avatar', 'active', 'provider_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * Storage path name
     *
     * @var string
     */
    public $path = 'avatars';

    /**
     * Default Super Admin ID
     *
     * @var int
     */
    const SUPER_ADMIN = 1;

    /**
     * Default Customer ID
     *
     * @var int
     */
    const CUSTOMER_ID = 3;

    /**
     * Validation rules
     *
     * @return array
     */
    public function rules()
    {
        $passwordRequired = !$this->id ? '|required|min:8|' : '';
        $exceptId = $this->id ? ',' . $this->id : '';

        return [
            'email' => 'required|max:255|email|unique:users,email' . $exceptId,
            'last_name' => 'required|max:65',
            'first_name' => 'required|max:65',
            'phone' => 'required|max:14|regex:/^\+?\d+( \d+)*$/',
            'address' => 'max:255',
            'city' => 'max:64',
            'country' => 'max:15',
            'password' => 'confirmed' . $passwordRequired,
            'password_confirmation' => 'same:password' . $passwordRequired,
            'avatar' => 'image|mimes:jpeg,png,jpg,gif|max:1024',
            'active' => 'boolean',
        ];
    }

    /**
     * Crypt password before save
     *
     * @param string $password
     * @return void
     */
    public function setPasswordAttribute($password)
    {
        if (!empty($password)) {
            $this->attributes['password'] = bcrypt($password);
        }
    }

    /**
     * Concat user first and last name
     *
     * @return string
     */
    public function getFullNameAttribute()
    {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }

    public function provider()
    {
        return $this->hasOne('App\Models\Deal\Provider');
    }

    public function seller()
    {
        return $this->hasOne('App\Models\Deal\Seller');
    }

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

}

app/Http/Controllers/Frontend/Common/ContactController.php
<?php

namespace App\Http\Controllers\Frontend\Common;

use App\Http\Controllers\FrontendController;
use Illuminate\Http\Request;
use App\Models\Common\Contact;
use App\Services\MailService;

class ContactController extends FrontendController
{

    /**
     * The MailService instance.
     *
     * @var MailService
     */
    public $mailService;

    /**
     * @param Request $request
     * @param Contact $contact
     * @param MailService $mailService
     *
     * @return void
     */
    public function __construct(Request $request, Contact $contact, MailService $mailService)
    {
        $this->mailService = $mailService;
        parent::__construct($request, $contact);
    }

    /**
     * Handle create request.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        \SEO::setTitle('Contactez-nous');
        return view('frontend.contents.common.contact.form');
    }

    /**
     * Store a newly created resource
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        $attributes = $this->currentRequest->all();
        $validator = $this->currentModel->validator($attributes);
        if ($validator->fails()) {
            flash()->error(trans('contact.cannot_save'));

            return redirect()->back()->withErrors($validator)->withInput($attributes);
        } else {
            $this->currentModel->fill($attributes);
            if ($this->currentModel->save()) {
                $this->mailService->sendContactRequest($this->currentModel);
                flash()->success(trans('contact.contact_success'));

                return redirect()->route('frontend.contact.index');
            }
        }
    }

}

app/Http/Controllers/Frontend/Common/NewsletterController.php
<?php

namespace App\Http\Controllers\Frontend\Common;

use App\Http\Controllers\FrontendController;
use Illuminate\Http\Request;
use App\Models\Common\Newsletter;
use Carbon\Carbon;

class NewsletterController extends FrontendController
{

    /**
     * @param Request $request
     * @param Newsletter $newsletter
     *
     * @return void
     */
    public function __construct(Request $request, Newsletter $newsletter)
    {
        parent::__construct($request, $newsletter);
    }

    /**
     * Store a newly created resource
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        $attributes = $this->currentRequest->all();
        $validator = $this->currentModel->validator($attributes);
        if ($validator->fails()) {
            return response()->json(['success' => false, 'message' => trans('newsletter.error_subscription')]);
        }

        $this->currentModel->fill($attributes);
        $this->currentModel->save();

        return response()->json(['success' => true, 'message' => trans('newsletter.success_subscription')]);
    }

    public function create()
    {
        $attributes = $this->currentRequest->all();
        if (empty($attributes['birth_date'])) {
            unset($attributes['birth_date']);
        } else {
            $attributes['birth_date'] = Carbon::createFromFormat('d/m/Y', $attributes['birth_date'])->toDateTimeString();
        }
        $validator = $this->currentModel->validator($attributes);
        if ($validator->fails()) {
            flash()->error($validator->errors()->first());

            return redirect()->back()->withErrors($validator)->withInput($attributes);
        }

        $this->currentModel->fill($attributes);
        if ($this->currentModel->save()) {
            try {
                $sources = [1 => 'Site web', 2 => 'LP Champions league', 3 => 'LP PS4', 4 => 'LP Women'];
                $civilities = [1 => 'Mlle.', 2 => 'Mme.', 3 => 'Mr.'];
                $post['firstname'] = $attributes['first_name'];
                $post['lastname'] = $attributes['last_name'];
                $post['email'] = $attributes['email'];
                $post['field[1]'] = 'Prospect';
                $post['field[3]'] = $attributes['birth_date'];
                $post['field[2]'] = $civilities[$attributes['civility']];
                $post['field[4]'] = $sources[$attributes['source']];
                $post['u'] = '1';
                $post['f'] = '1';
                $post['s'] = '';
                $post['c'] = '0';
                $post['m'] = '0';
                $post['act'] = 'sub';
                $post['v'] = '2';
                $ch = curl_init('https://guichetma.activehosted.com/proc.php');
                curl_setopt($ch, CURLOPT_HEADER, 0);
                curl_setopt($ch, CURLOPT_POST, 1);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
                curl_exec($ch);
                curl_close($ch);
            } catch (\Exception $e) {

            }
        }
        flash()->success('Votre inscription a bien été prise en compte.');

        return redirect()->back();
    }

}

app/Http/Controllers/Frontend/Common/ProfileController.php
<?php

namespace App\Http\Controllers\Frontend\Common;

use App\Http\Controllers\FrontendController;

class ProfileController extends FrontendController
{
    /**
     * profile index controller.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        \SEO::setTitle('Mon compte - Profil');
        return view('frontend.contents.common.user.profile')
            ->with('user', auth()->user());
    }

    /**
     * update user profile
     *
     * @return \Illuminate\Http\Response
     */
    public function update()
    {
        $user = auth()->user();
        $attributes = $this->currentRequest->all();
        $attributes['email'] = $user->email;
        $validator = $user->validator($attributes);
        if ($validator->fails()) {
            flash()->error(trans('user.cannot_save'));
            return redirect()->back()->withErrors($validator)->withInput($attributes);
        }
        if ($user->update($attributes)) {
            flash()->success('Informations mises à jour avec succès.');
        }

        return view('frontend.contents.common.user.profile')
            ->with('user', auth()->user());
    }

}

app/Http/Controllers/Frontend/Content/FaqController.php
<?php

namespace App\Http\Controllers\Frontend\Content;

use App\Http\Controllers\FrontendController;
use Illuminate\Http\Request;
use App\Models\Content\Faq;

class FaqController extends FrontendController
{

    /**
     * @param Request $request
     * @param Faq $faq
     *
     * @return void
     */
    public function __construct(Request $request, Faq $faq)
    {
        parent::__construct($request, $faq);
    }

    /**
     * List FAQ
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $faqs = $this->currentModel->select(['id', 'title', 'content'])->active()->get();

        \SEO::setTitle('Aide / Foire aux questions');

        return view('frontend.contents.content.faq.index')->with('faqs', $faqs);
    }

}

app/Http/Controllers/Frontend/Content/PageController.php
<?php

namespace App\Http\Controllers\Frontend\Content;

use App\Http\Controllers\FrontendController;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use App\Models\Content\Page;

class PageController extends FrontendController
{

    /**
     * @param Request $request
     * @param Page $page
     *
     * @return void
     */
    public function __construct(Request $request, Page $page)
    {
        parent::__construct($request, $page);
    }

    /**
     * View page details
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function view($id)
    {
        $page = $this->currentModel->findOrFail($id, ['id', 'title', 'content', 'active']);

        if (!$page->active) {
            throw (new ModelNotFoundException)->setModel(get_class($this->currentModel), $id);
        }

        \SEO::setTitle($page->seo->seo_title ? $page->seo->seo_title : $page->title);
        \SEO::setDescription($page->seo->seo_description);
        \SEO::opengraph()->setUrl(config('app.url') . $page->seo->seo_alias);
        \SEO::setCanonical(config('app.url') . $page->seo->seo_alias);
        \SEO::opengraph()->addProperty('type', 'articles');

        return view('frontend.contents.content.page.view')->with('page', $page);
    }

}

app/Http/Controllers/Frontend/Content/PostController.php
<?php

namespace App\Http\Controllers\Frontend\Content;

use App\Http\Controllers\FrontendController;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use App\Models\Content\Post;
use App\Models\Content\CategoryPost;

class PostController extends FrontendController
{

    /**
     * @param Request $request
     * @param Post $post
     *
     * @return void
     */
    public function __construct(Request $request, Post $post)
    {
        parent::__construct($request, $post);
    }

    /**
     * List posts
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = $this->currentModel->select(['id', 'title', 'category_id', 'content', 'image', 'created_at'])->active()->orderBy('created_at', 'desc')->paginate(12);

        \SEO::setTitle('Actualités des festivals et recommandations - Guichet Magazine');

        return view('frontend.contents.content.post.index')
            ->with('posts', $posts)
            ->with('categories', (new CategoryPost)->where('active', '=', 1)->get());
    }

    /**
     * View post details
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function view($id)
    {
        $post = $this->currentModel->findOrFail($id, ['id', 'title', 'content', 'active', 'image', 'created_at']);

        if (!$post->active) {
            throw (new ModelNotFoundException)->setModel(get_class($this->currentModel), $id);
        }

        $previous = $this->currentModel->where('id', '<', $id)->orderBy('id', 'desc')->first();
        $next = $this->currentModel->where('id', '>', $id)->orderBy('id', 'asc')->first();

        \SEO::setTitle(($post->seo->seo_title ? $post->seo->seo_title : $post->title) . ' - Guichet Magazine');
        \SEO::setDescription($post->seo->seo_description);
        \SEO::opengraph()->setUrl(config('app.url') . $post->seo->seo_alias);
        \SEO::setCanonical(config('app.url') . $post->seo->seo_alias);
        \SEO::opengraph()->addProperty('type', 'articles');

        return view('frontend.contents.content.post.view')
            ->with('post', $post)
            ->with('previous', $previous)
            ->with('categories', (new CategoryPost)->where('active', '=', 1)->get())
            ->with('next', $next);
    }

    public function category($id)
    {
        $category = (new CategoryPost)->where('id', '=', $id)->where('active', '=', 1)->first();
        if (!$category) {
            throw (new ModelNotFoundException)->setModel(get_class(CategoryPost), $id);
        }

        $posts = $this->currentModel->select(['id', 'title', 'category_id', 'content', 'image', 'created_at'])
            ->active()->where('category_id', $id)->orderBy('created_at', 'desc')->paginate(12);

        \SEO::setTitle(($category->seo->seo_title ? $category->seo->seo_title : $category->name) . ' - Guichet Magazine');
        \SEO::setDescription($category->seo->seo_description);
        \SEO::opengraph()->setUrl(config('app.url') . $category->seo->seo_alias);
        \SEO::setCanonical(config('app.url') . $category->seo->seo_alias);
        \SEO::opengraph()->addProperty('type', 'articles');

        return view('frontend.contents.content.post.index')
            ->with('posts', $posts)
            ->with('categories', (new CategoryPost)->where('active', '=', 1)->get());
    }


}

app/Http/Controllers/Frontend/Deal/CategoryController.php
<?php

namespace App\Http\Controllers\Frontend\Deal;

use App\Http\Controllers\FrontendController;
use App\Models\Deal\Category;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class CategoryController extends FrontendController
{
    /**
     * Display category page
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function view($id)
    {
        $category = (new Category)->findOrFail($id);
        if (!$category->active) {
            throw (new ModelNotFoundException)->setModel(Category::class, $id);
        }

//        $pub = 'pub-voyage.jpg';
//        if ($category->id == 2) {
//            $pub = 'pub-food.jpg';
//        }
//        if ($category->id == 3) {
//            $pub = 'pub-loisir.jpg';
//        }
//        if (in_array($category->id, [4, 5, 6, 7, 8])) {
//            $pub = 'pub-billeterie.jpg';
//        }

        $seo = $category->seo;
        \SEO::setTitle(($seo->seo_title ? $seo->seo_title : $category->title) . ' - Guichet.ma');
        \SEO::setDescription($seo->seo_description);
        \SEO::opengraph()->setUrl(config('app.url') . $seo->seo_alias);
        \SEO::setCanonical(config('app.url') . $seo->seo_alias);
        \SEO::opengraph()->addProperty('type', 'articles');

        $deals = $category->currentEvents();
        $events = $category->pastEvents()->paginate(9);

        $slides = $category->findDeals(6, true)->get();

        return view('frontend.contents.deal.category.index')->with(compact('category', 'deals', 'slides', 'events'));
    }
}

resources/views/frontend/partials/categories.blade.php
<div class="widget widget-menu">
    <div class="hr-link orange">
        <hr class="mBtm-50 mTop-30">
        <h3 class="list-title">Deals Catégories</h3>
    </div>
    <ul class="nav sidebar-nav">
        @foreach($listCategories as $cat)
            @php $count = $cat->children()->count() @endphp
            @if(!$count)
                <li>
                    <a href="/{{ $cat->seo->seo_alias }}">
                        <i class="{{ $cat->icon }}"></i> {{ $cat->title }}
                    </a>
                </li>
            @else
                <li class="dropdown">
                    <a class="ripple-effect dropdown-toggle" href="#" data-toggle="dropdown">
                        <i class="{{ $cat->icon }}"></i> {{ $cat->title }}
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        @foreach($cat->children as $child)
                            <li>
                                <a href="/{{ $child->seo->seo_alias }}">
                                    <i></i> {{ $child->title }}
                                </a>
                            </li>
                        @endforeach
                    </ul>
                </li>
            @endif
        @endforeach
    </ul>
</div>

resources/views/frontend/partials/info.blade.php
<div class="inner-side shadow mTop-0">
    <div class="widget">
        <div class="hr-link orange">
            <hr class="mBtm-50 mTop-30">
            <h3 class="list-title">@lang('contact.contact_info')</h3>
        </div>
        <address>
            <p>
                <i class="fa fa-map-marker"></i> {{ Setting::get('address_1') }}
                <br>
                @if (Setting::has('address_2'))
                    {{ Setting::get('address_2') }}
                    <br>
                @endif
                {{ Setting::get('zip_code') . ' ' . Setting::get('city') . ' - ' . Setting::get('country') }}
            </p>
            <p><i class="fa fa-phone"></i> {{ Setting::get('phone') }}</p>
            <p><i class="fa fa-envelope"></i> {{ Setting::get('email') }}</p>
        </address>
    </div>
</div>

resources/views/frontend/partials/share.blade.php
<div class="entry-share mTop-10">
    <div class="helper"> @lang('front.share_or_save_this_post') </div>
    <ul class="social social-share-btn">
        <li>
            <a class="social-btn social-facebook" target="_blank"
               href="{{ Share::load($share_url, $share_title)->facebook() }}">
                <i class="ti-facebook"></i>
            </a>
        </li>
        <li>
            <a class="social-btn social-twitter" target="_blank"
               href="{{ Share::load($share_url, $share_title)->twitter() }}">
                <i class="ti-twitter"></i>
            </a>
        </li>
        <li>
            <a class="social-btn social-pinterest" target="_blank"
               href="{{ Share::load($share_url, $share_title)->pinterest() }}">
                <i class="ti-pinterest"></i>
            </a>
        </li>
        <li>
            <a class="social-btn social-linkedin" target="_blank"
               href="{{ Share::load($share_url, $share_title)->linkedin() }}">
                <i class="ti-linkedin"></i>
            </a>
        </li>
        <li>
            <a class="social-btn social-google" target="_blank"
               href="{{ Share::load($share_url, $share_title)->gplus() }}">
                <i class="ti-google"></i>
            </a>
        </li>
    </ul>
    {{--<div class="like-btn">--}}
        {{--<iframe src="https://www.facebook.com/plugins/like.php?href={{ $share_url }}&width=85&layout=button_count&action=like&size=small&show_faces=false&share=false&height=21&appId"--}}
                {{--width="85" height="21" style="border:none;overflow:hidden" scrolling="no" frameborder="0"--}}
                {{--allowTransparency="true" allow="encrypted-media"></iframe>--}}
    {{--</div>--}}
</div>

resources/views/frontend/partials/ticket.blade.php
<html>
<head>
    <style>
        @page {
            size: auto;
            margin-top: 0;
            margin-right: 0;
            margin-bottom: 0;
            margin-left: 0;
        }

        .page {
            background-image: url('/frontend/images/ticket-enligne-guichet.png');
            background-size: 100%;
            background-repeat: no-repeat;
            height: 484px;
            width: 933px;
            padding: 0;
            color: rgb(34, 34, 34);
            font-family: monospace;
            font-weight: 900;
        }

        .ticket-left {
            float: left;
            width: 335px;
            padding-left: 35px;
            padding-top: 90px;
        }

        .ticket-center {
            float: left;
            width: 105px;
            padding-top: 10px;
        }

        .ticket-right {
            float: right;
            width: 120px;
            text-align: center;
            padding-top: 50px;
        }

        .container {
            height: 110px;
        }

        .provider {
            font-family: 'moskmedium';
            font-size: 11pt;
        }

        .title {
            font-family: 'moskextrabold';
            text-transform: uppercase;
        }

        .custom-date {
            font-family: 'moskmedium';
            font-size: 14pt;
            text-transform: capitalize;
        }

        .user {
            font-family: 'mosklight';
            font-size: 14pt;
            height: 25px;
        }

        .price {
            font-family: 'moskmedium';
            font-size: 12pt;
        }

        .place {
            font-family: 'moskextrabold';
            font-size: 20px;
            margin-left: 200px;
            height: 50px;
            margin-top: -25px;
            text-align: right;
        }

        .footer {
            font-family: 'moskmedium';
            font-size: 9pt;
            float: left;
            width: 72%;
            padding-left: 35px;
        }

        .footer div {
            width: 50%;
            float: left;
        }

        .ticket-right .address {
            font-family: 'moskmedium';
            font-size: 8pt;
            width: 90px;
            margin: 0 auto;
            height: 40px;
        }

        .ticket-right .date {
            font-family: 'moskextrabold';
            font-size: 8pt;
            width: 100px;
            margin: 0px auto;
            height: 50px;
        }

        .ticket-right .price {
            font-family: 'moskextrabold';
            font-size: 10pt !important;
        }

        .ticket-right .place {
            font-family: 'moskextrabold';
            font-size: 10.3pt;
            margin-top: 20px;
            text-align: center !important;
        }


    </style>
</head>

<body>

@foreach($order->lines as $line)
    @foreach($line->tickets as $ticket)
        {{--@if (!empty($line->offer->deal->custom_ticket))--}}
        {{--<style>--}}
        {{--.page {--}}
        {{--background-image: url({{ '/imagecache/original/' . $line->offer->deal->custom_ticket }});--}}
        {{--}--}}
        {{--</style>--}}
        {{--@endif--}}
        @if ($isOffile)
            <style>
                .page {
                    background-image: none;
                }
            </style>
        @endif
        <div class="page">
            <div class="ticket-left">
                <div class="container">
                    <div class="provider">
                        {{ $line->offer->deal->provider->title }}
                    </div>
                    @if (strlen($line->product_name) > 180)
                        <div class="title" style="font-size: 14px">
                            {{ $line->product_name }}
                        </div>
                    @elseif (strlen($line->product_name) > 160)
                        <div class="title" style="font-size: 16px">
                            {{ $line->product_name }}
                        </div>
                    @elseif (strlen($line->product_name) > 110)
                        <div class="title" style="font-size: 18px">
                            {{ $line->product_name }}
                        </div>
                    @elseif (strlen($line->product_name) > 80)
                        <div class="title" style="font-size: 18px">
                            {{ $line->product_name }}
                        </div>
                    @elseif (strlen($line->product_name) > 40)
                        <div class="title" style="font-size: 23px">
                            {{ $line->product_name }}
                        </div>
                    @else
                        <div class="title" style="font-size: 24px">
                            {{ $line->product_name }}
                        </div>
                    @endif
                    <div class="custom-date">
                        {{ str_limit($line->offer->deal->custom_field, 50, '...') }}
                    </div>
                </div>
                <div class="user">
                    @if($order->user && !$order->offered)
                        {{ $order->user->full_name }}
                    @endif
                    @if($order->offered && $order->offered_by)
                        Invitation offerte par {{ $order->offered_by }}
                    @endif
                </div>
                <div class="price">
                    @if($order->offered)
                        Ticket Offert
                    @else
                        {{ number_format($line->product_price, 0) }} Dhs
                    @endif
                    - <span>{{ $line->offer_name }}</span>
                </div>
                <div class="place">
                    @if($ticket->seat)
                        @if(($line->offer->deal->seating_plan_id == 8 || $line->offer->deal->seating_plan_id == 10 || $line->offer->deal->seating_plan_id == 13) && strtolower($line->offer_name) == 'balcon')
                            <span style="font-size: 16px">Placement libre</span>
                        @else
                            PLACE <span>{{ $ticket->seat }}</span>
                        @endif
                    @endif
                </div>
            </div>
            <div class="ticket-center">
                @if ($line->offer->deal->barcode_type)
                    <img src="{{ url('/tickets/barcode/'. $ticket->id . '/80.png') }}">
                @else
                    <img src="{{ url('/tickets/qrcode/'. $ticket->id . '/80.png') }}">
                @endif
            </div>
            <div class="ticket-right">
                @if ($line->offer->deal->barcode_type)
                    <img src="{{ url('/tickets/barcode/'. $ticket->id . '/50.png') }}">
                @else
                    <img src="{{ url('/tickets/qrcode/'. $ticket->id . '/50.png') }}">
                @endif
                <div class="address">
                    {{ str_limit($line->offer->deal->address, 65, '...') }}
                </div>
                <div class="date">
                    {{ str_limit($line->offer->deal->custom_field, 90, '...') }}
                </div>
                <div class="price">
                    @if($order->offered)
                        Ticket Offert
                    @else
                        {{ number_format($line->product_price, 0) }} Dhs
                    @endif
                    <br/>
                    <span>{{ $line->offer_name }}</span>
                </div>
                <div class="place">
                    @if($ticket->seat)
                        @if(($line->offer->deal->seating_plan_id == 8 || $line->offer->deal->seating_plan_id == 10 || $line->offer->deal->seating_plan_id == 13) && strtolower($line->offer_name) == 'balcon')
                            <span style="font-size: 9pt">Placement libre</span>
                        @else
                            PLACE <span>{{ $ticket->seat }}</span>
                        @endif
                    @endif
                </div>
            </div>
            <div class="footer">
                <div class="ticket">
                    TICKET : {{ $ticket->number }}
                </div>
                <div class="bought">
                    Achat {{ $order->created_at }}
                </div>
                <div class="address">
                    {{ str_limit($line->offer->deal->address, 100, '...') }}
                </div>
                <div class="address">
                    {{ str_limit($line->offer->deal->address, 100, '...') }}
                </div>
            </div>
        </div>
    @endforeach
@endforeach

</body>
</html>